server:
    port: ${SERVER_PORT:8080}

spring:
    application:
        name: api-gateway
    profiles:
        default: local
    cloud:
        gateway:
            server:
                webmvc:
                    routes:
                        - id: ms-proyectos
                          uri: lb://MS-PROYECTOS
                          predicates:
                              - Path=/api/proyectos,/api/proyectos/**
                        - id: ms-equipos
                          uri: lb://MS-EQUIPOS
                          predicates:
                              - Path=/api/equipos,/api/equipos/**
                        - id: ms-tareas
                          uri: lb://MS-TAREAS
                          predicates:
                              - Path=/api/tareas,/api/tareas/**

eureka:
    client:
        enabled: ${EUREKA_CLIENT_ENABLED:true}
    instance:
        prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}

management:
    endpoints:
        web:
            exposure:
                include: health,info,gateway
    endpoint:
        health:
            show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS:always}
