server:
    port: ${SERVER_PORT:8090}

spring:
    application:
        name: bff-service
    profiles:
        default: local

eureka:
    client:
        enabled: ${EUREKA_CLIENT_ENABLED:true}
    instance:
        prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}

management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS:always}

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /swagger-ui.html

app:
    cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
