eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
  server:
    enable-self-preservation: ${EUREKA_SELF_PRESERVATION:false}
