server:
    port: ${SERVER_PORT:8761}

spring:
    application:
        name: eureka-server
    profiles:
        default: local

management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS:always}
